global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi-depression-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]
        labels:
          app: "student-depression-api"
          environment: "development"
    scrape_interval: 10s

  - job_name: "render-prod-api"
    scheme: https
    metrics_path: "/metrics"
    static_configs:
      - targets: ["student-depression-predictor-c3ce.onrender.com"]
        labels:
          app: "student-depression-api"
          environment: "production"
    scrape_interval: 30s
