global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi-depression-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]
        labels:
          app: "student-depression-api"
          environment: "development"
    scrape_interval: 10s
